server:
  http2:
    enabled: false
  port: 9000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: bnpl-microfinance
    key-alias: bnpl-microfinance
    protocol: TLS
    enabled: false


enable.controller.default: true
enable.controller.custom: true