spring:
  batch:
    job:
      enabled: true
    jdbc:
      schema: classpath:/org/springframework/batch/core/schema-postgresql.sql
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  rabbitmq:
    username: user
    password: password
    host: localhost
server:
  port: 8090
